### Cadastro de usuário
POST https://fatecpi-cesarvidros-1.onrender.com/auth/register
Content-Type: application/json

{
  "nome": "pedro",
  "email": "pedro.marcos@email.com",
  "senha": "pedro1",
  "tipo_acesso": "user",
  "data_nascimento": "2000-01-01"
}

### Cadastro de endereço
POST http://localhost:3001/auth/endereco
Content-Type: application/json

{
  "usuario_id": 35,
  "rua": "Rua dos Passarinhos",
  "estado": "SP",
  "cidade": "São Paulo",
  "numero": "222"
}

### Cadastro de telefone
POST http://localhost:3001/auth/telefone
Content-Type: application/json

{
  "usuario_id": 35,
  "numero": "12999999999"
}

### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "pedro@email.com",
  "senha": "pedro123"
}